# Generated by Django 4.2 on 2023-04-06 13:47

import account.custom_validators
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, validators=[django.core.validators.MinLengthValidator(3), account.custom_validators.check_only_characters_in_name], verbose_name='Name')),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('email', models.EmailField(error_messages={'unique': 'A Email with that Emails already exists.'}, max_length=254, unique=True, verbose_name='Email')),
                ('data_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data joined')),
                ('data_change_info', models.DateTimeField(auto_now=True, verbose_name='Data change info')),
                ('is_active', models.BooleanField(default=False)),
                ('auth_user', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
        ),
    ]
