version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: v1

  adminer:
    image: adminer
    restart: always
    ports:
      - "8000:8000"






#  postgres:
#      image: postgres:alpine
#      restart: always
#      expose:
#        - 5432
#      volumes:
#        - "./init/postgres:/docker-entrypoint-initdb.d"
#        - "./data/postgres_data:/var/lib/postgresql/data"
#      environment:
#        POSTGRES_DB:       postgres
#        POSTGRES_USER:     postgres
#        POSTGRES_PASSWORD: v1